### ISSUE TITLE
Abandoned dependency on herrara-io/version

### ISSUE THREAD

**Issue by dbergunder** [shivas/versioning-bundle#25]
Any chance on replacing the abandoned ```"herrera-io/version": "~1.0"``` [package](https://github.com/kherge-abandoned/php-version) and replace it with something like [composer/semver](https://github.com/composer/semver) or a forked version we can maintain?

**Comment by shivas** [comment]
It's already done, try 2.0.0-alpha version

**Comment by dbergunder** [comment]
Ah, well thanks! 😄
