### ISSUE TITLE
Faulty check for capistrano environment with file_get_contents

### ISSUE THREAD

**Issue by bblue** [shivas/versioning-bundle#26]
I am getting the following errors:

`file_get_contents(/var/www/app/../REVISION): failed to open stream: No such file or directory in /var/www/vendor/shivas/versioning-bundle/Shivas/VersioningBundle/Handler/CapistranoHandler.php on line 95`

This is caused by 

```
    private function isCapistranoEnv()
    {
        try {
           file_get_contents($this->path . 'REVISION');
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }
```

`file_get_contens `does not throw an exception on failure, it returns false. 

http://php.net/manual/en/function.file-get-contents.php#refsect1-function.file-get-contents-returnvalues
> The function returns the read data or FALSE on failure.

**Comment by dmvslv** [comment]
I have faced with same issue on prod. It was fixed by @mdriessen here https://github.com/shivas/versioning-bundle/pull/19
You can try dev-master or dev-2.0.0-alpha.

@shivas  Do you have any plans to add a new release for v1?

**Comment by shivas** [comment]
It would be nice if you guys test 2.0.0-alpha and let me know if everything is fine there. And yes, i'll add release for v1

**Comment by bblue** [comment]
I can do some testing with the 2.0 version this weekend.

**Comment by shivas** [comment]
1.4.2 tagged on current master
