### ISSUE TITLE
herrera-io/version is abandoned preRelease/build are truncated

### ISSUE THREAD

**Issue by Toilal** [shivas/versioning-bundle#27]
[herrera-io/version](https://github.com/kherge-abandoned/php-version) is abandoned, and I have found an issue in this dependency.

Would you consider migrating to another dependency, maybe [composer/semver]( https://github.com/composer/semver) would be a good choice ?

Problem is here : https://github.com/kherge-abandoned/php-version/blob/master/src/lib/Herrera/Version/Parser.php#L70 and https://github.com/kherge-abandoned/php-version/blob/master/src/lib/Herrera/Version/Parser.php#L76. 

`build` and `preRelease` may be truncated if they contains `+` and `-`.

```
list($version, $build) = explode('+', $version);
```

 should be replaced with

```
list($version, $build) = explode('+', $version, 2);
```

**Comment by shivas** [comment]
try dev-master, its already migrated to different library

**Comment by shivas** [comment]
or even: 2.0.0-alpha branch

**Comment by Toilal** [comment]
Yes, alpha branch is really better with the refactoring of `Handler` into `Provider`/`Formatter`.

I only have to define a null formatter to do exactly what I want (=raw git describe output). Do you plan a release on packagist soon ?

Thanks :+1:
