### ISSUE TITLE
Symfony 4.3 deprecation warning about TreeBuilder root

### ISSUE THREAD

**Issue by BlackWiCKED** [shivas/versioning-bundle#45]
The following deprecation warnings are shown for Symfony 4.3:

> A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

> The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "shivas_versioning" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

Both warnings are coming from this file: **_DependencyInjection/Configuration.php_**

**Comment by dontub** [comment]
Fixed with #52.
