### ISSUE TITLE
Support for git hashes

### ISSUE THREAD

**Issue by SteppingHat** [shivas/versioning-bundle#46]
I'd be happy to contribute to this if its in the scope for the project, but would it be feasible to support git commit hashes as a provider? This breaks away from the semantic versioning that the bundle aims to provide, but I believe that there is some value to provide at least the option to choose this form of versioning.

**Comment by dontub** [comment]
This bundle uses a version class that enforces the syntax of a semantic version number. How would a version number of this provider look like?
