### ISSUE TITLE
Get an exception on version bump

### ISSUE THREAD

**Issue by metalmini** [shivas/versioning-bundle#6]
Hi,

i get an error when i run the app:version:bump

  [RuntimeException]                                           
  Git tag describe handler describe returned no valid version 

The command(s) i am running 
 bin/console app:version:bump --minor
 bin/console app:version:bump --minor 1.3.0
 bin/console app:version:bump --minor 1

The only command that seems to do something is:
 bin/console app:version:bump 1.2.0

Correct me if i'm wrong but does the bump command without a version number do a +1 one a major, minor or patch number?

**Comment by shivas** [comment]
Intresting, can you copy paste some output here?

- app:version:bump -l
- app:version:bump -vvv

Without any parameters command trying to get version from available version handlers, thats the exception you get... "Git tag describe handler describe returned no valid version" means you running it in git repository, though no valid tags for version available.

Can you paste "git branch" output too? if there is no sensitive information of course.

**Comment by metalmini** [comment]
Problem is solved. We had a tag, which was very old. But this tag had the wrong format. This caused the error. As you said ;-)

**Comment by shivas** [comment]
good, closing issue then.
