### ISSUE TITLE
Symfony 4.4 / Twig 3 compatibility

### ISSUE THREAD

**Issue by mikatrash** [shivas/versioning-bundle#62]
Hi,

We encountered this issue since we updated to SF4.4.
Twig's GlobalInterface is TypeHinted (https://github.com/twigphp/Twig/commit/54cec4e3b8555fbb40c8dd7c6642e9f21607010d#diff-08b21707843379a1fde275ef7f0a2b49) so VersionExtension doesn't implement the interface.

Declaration of Shivas\VersioningBundle\Twig\VersionExtension::getGlobals() must be compatible with Twig\Extension\GlobalsInterface::getGlobals(): array in C:\WorkspacesEclipse\TRUNK\eLogikSupport\vendor\shivas\versioning-bundle\Twig\VersionExtension.php on line 12

**Comment by dontub** [comment]
Fixed by #63.
