### ISSUE TITLE
Update to nikolaposa/version 4.0.0

### ISSUE THREAD

**Issue by Knallcharge** [shivas/versioning-bundle#69]
Currently in use is 3.2.0, is it possible to update?

**Comment by dontub** [comment]
Because of the changed API of nikolaposa/version 4 some adaptions are necessary. Would you like to make a PR?

**Comment by Knallcharge** [comment]
Tried a quick fix but was not successful, obviously the changes inside nikolaposa/version 4 are bigger than expected. Maybe someone with more knowledge of version can help.
